# Generated by Django 5.1.7 on 2025-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cryptcurrencyratemodel',
            fields=[
                ('currencytype', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doller', models.FloatField()),
                ('rupee', models.FloatField()),
                ('originalprice', models.FloatField()),
            ],
            options={
                'db_table': 'currencyrate',
            },
        ),
        migrations.CreateModel(
            name='CurrencyUpdateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currencyname', models.CharField(max_length=100)),
                ('conversionRate', models.FloatField()),
                ('newCurrencyValue', models.FloatField()),
                ('originalCurrencyValue', models.FloatField()),
                ('chnageValue', models.FloatField()),
                ('profitorloss', models.CharField(max_length=50)),
                ('changedate', models.DateTimeField()),
            ],
            options={
                'db_table': 'currencychnagetable',
                'unique_together': {('currencyname', 'changedate')},
            },
        ),
    ]
